Cruises/Cruises.WebApp/Models/ErrorViewModel.cs
using System;

namespace Cruises.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Cruises/Cruises.WebApp/Controllers/HomeController.cs
using Cruises.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Cruises.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Cruises/Cruises.WebApp/Controllers/VoyagesController.cs
using Cruises.Service;
using Cruises.ViewModels.Voyages;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Cruises.WebApp.Controllers
{
    public class VoyagesController : Controller
    {
        private readonly VoyageService voyagesService;
        public VoyagesController()
        {
            voyagesService = new VoyageService();
        }
        public IActionResult Index(int page = 1)
        {
            VoyagesIndexViewModel models = new VoyagesIndexViewModel();
            models.PageNumber = page;
            models= voyagesService.GetVoyages(models);
            return View(models);
        }
        public IActionResult Cheapest()
        {
            List<VoyageIndexViewModel> model = voyagesService.GetCheapestVoyages();
            return View(model);
        }

        public IActionResult Expensive()
        {
            List<VoyageIndexViewModel> model = voyagesService.GetMostExpensiveVoyages();
            return View(model);
        }
    }
}

Cruises/Cruises.WebApp/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enchanted Escala Cruises</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
        }

        #header {
            position: relative;
            height: 100vh;
            background: linear-gradient(rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.8)), url('https://a-z-animals.com/media/2022/11/Atlantic-Ocean.jpg') no-repeat;
            background-size: cover;
            display: flex;
            justify-content: center;
            align-items: center;
            text-align: center;
            font-family: Gabriola;
            color: DarkOrchid;
        }

        #header h1 {
            margin: 0;
            padding: 20px;
            font-size: 4.5rem;
            font-weight: bold;
        }

        #header p {
            margin: 0;
            padding: 20px;
            font-size: 2rem;
            font-weight: 600;
        }
    </style>
</head>
<body>
    <section id="header">
        <div>
            <h1>Enchanted Escala Cruises</h1>
            <p>Your Ultimate Destination for Unforgettable Voyages</p>
        </div>
    </section>
</body>
</html>

Cruises/Cruises.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cruises.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cruises.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Voyages" asp-action="Index">Voyages</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Voyages" asp-action="Cheapest">Cheapest voyages</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Voyages" asp-action="Expensive">Most expensive voyages</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Cruises.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Cruises/Cruises.WebApp/Views/Shared/_PagingPartial.cshtml
@model PagingViewModel
<nav aria-label="..." class="">
    <ul class="pagination  justify-content-center ">
        <li class="page-item @if (!Model.HasPreviousPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="@Model.Action" asp-route-page="@Model.PreviousPageNumber">
                <i class="fas fa-step-backward"></i>
                Previous
            </a>
        </li>
        @for (int i = Model.PageNumber - 2; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="@Model.Action" asp-route-page="@i">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 2; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="@Model.Action" asp-route-page="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="@Model.Action" asp-route-page="@Model.NextPageNumber"><i class="fas fa-step-forward"></i>Next</a>
        </li>
    </ul>
</nav>


@*<partial name="_PagingPartial" />*@

Cruises/Cruises.WebApp/Views/Voyages/Cheapest.cshtml
@model List<Cruises.ViewModels.Voyages.VoyageIndexViewModel>

	

<div class="jumbotron">
    <h2 class="display-4">Cheapest flights</h2>
    <hr />
    <div class="container">
        <div class="row mx-auto ">
            @foreach (var item in Model)
            {
                <div class="card mx-auto my-1" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">@item.Name</h5>
                        <p class="card-text">Start harbour: @item.StartHarbour</p>
                        <p class="card-text">Destination harbour: @item.DestinationHarbour</p>
                        <p class="card-text">Duration: @item.Duration</p>
                        <p class="card-text">Ship: @item.Ship</p>
                        <p class="card-text">Price: @item.TicketPrice</p>
                        <img class="img-thumbnail" src="@item.ImageUrl" />
                        @*<a href="#" class="btn btn-primary">Go somewhere</a>*@
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Cruises/Cruises.WebApp/Views/Voyages/Expensive.cshtml
@model List<Cruises.ViewModels.Voyages.VoyageIndexViewModel>


<div class="jumbotron">
    <h2 class="display-4">Most expensive voyages</h2>
    <hr />
    <div class="container">
        <div class="row mx-auto ">
            @foreach (var item in Model)
            {
                <div class="card mx-auto my-1" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">@item.Name</h5>
                        <p class="card-text">Start harbour: @item.StartHarbour</p>
                        <p class="card-text">Destination harbour: @item.DestinationHarbour</p>
                        <p class="card-text">Duration: @item.Duration</p>
                        <p class="card-text">Ship: @item.Ship</p>
                        <p class="card-text">Price: @item.TicketPrice</p>
                        <img class="img-thumbnail" src="@item.ImageUrl" />
                        @*<a href="#" class="btn btn-primary">Go somewhere</a>*@
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Cruises/Cruises.WebApp/Views/Voyages/Index.cshtml
@model Cruises.ViewModels.Voyages.VoyagesIndexViewModel

<h1>Voyages page</h1>


<table class="table table-bordered table-hover">
    <thead class="thead-light">
        <tr>
            <th>Name</th>
            <th>From</th>
            <th>To</th>
            <th>Duration</th>
            <th>Ship</th>
            <th>Price</th>
            <th>Image</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var p in Model.Voyages)
        {
            <tr>
                <td>@p.Name</td>
                <td>@p.StartHarbour</td>
                <td>@p.DestinationHarbour</td>
                <td>@p.Duration</td>
                <td>@p.Ship</td>
                <td>@p.TicketPrice</td>
                <td><img src="@p.ImageUrl" width="300px" height="150px" /></td>
            </tr>
        }
    </tbody>
    <tfoot>
    </tfoot>
</table>
<partial name="_PagingPartial" />